### ISSUE TITLE
Empty function

### ISSUE THREAD

**Issue by cmin764** [alk-language/k-semantics#6]
Compiling an empty function similar to this:

```alk
sort(out vec, len) {
}
```

will result in an error:

> [Error] Critical: Parse error: Syntax error near unexpected character '}'
> Source(/mnt/C/Repos/cmiN/FII/L1/PA/2/./sort.alk)
> Location(2,1,2,1)

**Comment by dlucanu** [comment]
The current definition of Alk does not allow such functions since we consider they are not useful .
You may include an empty block if you need such a function.
If we find an example where such functions are needed, then we shall extend the definition (it is quite easy to do it).

**Comment by cmin764** [comment]
Good to know that.
